version: "3"

services:
  backend:
    build:
      dockerfile: system/Dockerfile
      context: .
    container_name: tron_rest_service
    ports:
      - "8000:8000"
    env_file:
      - ./docker/backend/.env
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    container_name: tron_service_db
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgresql/.env
